import { Helmet } from "react-helmet";
import { Header } from "../Components/Header/Header";
import { IoStar, IoStarHalfOutline, IoStarOutline } from "react-icons/io5";
import { Button, Divider } from "antd";
import { RiDeleteBinLine } from "react-icons/ri";
import { BsLightningCharge } from "react-icons/bs";
import { FaTags } from "react-icons/fa";
import { Footer } from "../Components/Footer/Footer";

const Cart = () => {
  return (
    <div className="bg-slate-50/20">
      <Helmet>
        <title>My Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fursanFavIcon.svg" />
      </Helmet>
      <Header />
      <h1 className="text-2xl text-center my-5">My Cart</h1>
      <br />
      <br />
      <main className="mb-10 md:max-w-[80%] mx-auto relative grid md:grid-cols-2">
        <section className="px-2 bg-white w-full">
          <div className=" w-full pt-4 border my-2 shadow-sm ">
            <section className="flex items-center">
              <img
                src="../../public/products/img.jpg"
                width={100}
                height={100}
                alt="djs"
              />
              <div>
                <p>Ultra Wireless S50 Headphones S50 with Bluetooth</p>
                <div className="text-amber-400 flex gap-1 place-self-start my-3">
                  <IoStar />
                  <IoStar />
                  <IoStar />
                  <IoStarHalfOutline />
                  <IoStarOutline />
                </div>
              </div>
            </section>
            <section className="flex items-center gap-3 px-2">
              <div className="flex  ">
                <Button className="rounded-full">+</Button>
                <div className="w-10 flex justify-center items-center">1</div>
                <Button className="rounded-full">-</Button>
              </div>
              <div className="my-3">
                <p className="flex gap-2">
                  <span className="text-slate-400 line-through ">$4,699</span>
                  <b>$3,328</b>
                  <em className="text-green-600 font-bold">29% off</em>
                </p>
              </div>
            </section>
            <section className="border-t flex justify-around items-center ">
              <div className="hover:bg-slate-100 active:bg-slate-100 border-r w-full text-center flex justify-center items-center p-3 gap-1">
                <RiDeleteBinLine /> Remove
              </div>
              <div className="hover:bg-slate-100 active:bg-slate-100 w-full text-center flex justify-center items-center p-3 gap-1">
                <BsLightningCharge /> Buy this now
              </div>
            </section>
          </div>
          <div className=" w-full pt-4 border my-2 shadow-sm">
            <section className="flex items-center">
              <img
                src="../../public/products/img.jpg"
                width={100}
                height={100}
                alt="djs"
              />
              <div>
                <p>Ultra Wireless S50 Headphones S50 with Bluetooth</p>
                <div className="text-amber-400 flex gap-1 place-self-start my-3">
                  <IoStar />
                  <IoStar />
                  <IoStar />
                  <IoStarHalfOutline />
                  <IoStarOutline />
                </div>
              </div>
            </section>
            <section className="flex items-center gap-3 px-2">
              <div className="flex  ">
                <Button className="rounded-full">+</Button>
                <div className="w-10 flex justify-center items-center">1</div>
                <Button className="rounded-full">-</Button>
              </div>
              <div className="my-3">
                <p className="flex gap-2">
                  <span className="text-slate-400 line-through ">$4,699</span>
                  <b>$3,328</b>
                  <em className="text-green-600 font-bold">29% off</em>
                </p>
              </div>
            </section>
            <section className="border-t flex justify-around items-center ">
              <div className="hover:bg-slate-100 active:bg-slate-100 border-r w-full text-center flex justify-center items-center p-3 gap-1">
                <RiDeleteBinLine /> Remove
              </div>
              <div className="hover:bg-slate-100 active:bg-slate-100 w-full text-center flex justify-center items-center p-3 gap-1">
                <BsLightningCharge /> Buy this now
              </div>
            </section>
          </div>
          <section className="bg-white">
            <div>
              <form action="#" className="flex flex-wrap justify-center gap-5">
                <div className="border rounded-full  flex justify-between items-center">
                  <input
                    type="text"
                    placeholder="Coupon Code "
                    className=" rounded-l-full pl-3 w-full outline-none"
                  />
                  <div className="bg-black text-white rounded-r-full  h-full px-6 py-2">
                    <FaTags />
                  </div>
                </div>
                <Button
                  htmlType="submit"
                  className="rounded-full px-5 bg-slate-200 hover:bg-slate-400 hover:text-white hover:border-none active:bg-slate-400 focus:bg-slate-200"
                >
                  Update cart
                </Button>
              </form>
            </div>
          </section>
        </section>
        <Divider className="md:hidden" />

        <section className="w-full  pt-4 border my-5 shadow-sm px-2 ml-auto h-[19em] bg-white">
          <h3 className="font-bold">Price Details</h3>

          <table className="border-b border-dashed table-auto w-full leading-10">
            <tbody>
              <tr>
                <td>Price</td>
                <td className="text-right">$9,398</td>
              </tr>
              <tr>
                <td>Discount</td>
                <td className="text-right text-green-600 font-semibold">
                  -$2,742
                </td>
              </tr>
              <tr>
                <td>Delivery Charges</td>
                <td className="text-right text-green-600 font-semibold">
                  FREE Delivery
                </td>
              </tr>
              <tr className="border-t border-dashed">
                <td>Total Amount</td>
                <td className="text-right font-bold">$6,656</td>
              </tr>
            </tbody>
          </table>
          <p className="text-xs text-green-600 font-semibold my-5">
            You will save $2,742 on this order
          </p>
        </section>
        <section className="sticky bottom-0 shadow-sm py-2 px-5 flex justify-end w-full md:col-span-2">
          <Button className="h-10 bg-amber-400 font-bold rounded-md hover:bg-amber-500 active:bg-amber-500 focus:bg-amber-500 focus:border-none">
            Place Order
          </Button>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Cart;
