import React, { useEffect, useState } from "react";
import { UseQueryResult, useQuery } from "react-query";
import { APIClient } from "../utils/axios";
import { Link, useLocation } from "react-router-dom";
import { Helmet } from "react-helmet";
import { Header } from "../Components/Header/Header";
import { BiSlider } from "react-icons/bi";
import { MdKeyboardArrowDown } from "react-icons/md";
import { Drawer, Pagination, Rate } from "antd";
import { CartIcon } from "../Components/icons/CartIcon";
import { BackToTop } from "../Components/Common-Comp/BackToTop";
import { Footer } from "../Components/Footer/Footer";

const Categories = () => {
  const [open, setOpen] = useState(false);
  const [placement, setPlacement] = useState<DrawerProps["placement"]>("left");

  const location = useLocation();
  const queryParams = new URLSearchParams(location.search);
  const cat = queryParams.get("cat");

  const getCategoryProducts = async () => {
    return await APIClient.get(
      `https://dummyjson.com/products/category/${cat}`
    );
  };

  const {
    data,
    // isSuccess: catSucc,
    // isLoading: catloading,
  } = useQuery("getCategoryProducts", getCategoryProducts);

  // console.log("cat data: ", data);

  const showDrawer = () => {
    setOpen(true);
  };

  const onClose = () => {
    setOpen(false);
  };

  // console.log("slug: ",router.asPath);

  return (
    <div>
      <Helmet>
        <title>{cat}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fursanFavIcon.svg" />
      </Helmet>
      <Header />
      <h1 className="text-2xl font-semibold capitalize m-5"> {cat}</h1>
      <section>
        <div className="flex justify-between px-4 bg-slate-50 py-3 mx-3 rounded-lg">
          <div
            className="flex items-center gap-1 cursor-pointer"
            onClick={showDrawer}
          >
            <BiSlider className="font-extrabold" /> Filters
          </div>
          <div className="flex items-center gap-1 cursor-pointer">
            Default sorting <MdKeyboardArrowDown />{" "}
          </div>
        </div>
      </section>
      <main className="grid grid-cols-2 gap-1 p-2 md:grid-flow-col md:auto-cols-fr">
        {data?.data?.products.map((it: any, i: number) => (
          <div
            key={i}
            className="cursor-pointer bg-white odd:mr-1 border hover:scale-100 hover:shadow-md ease-in-out duration-300 p-3 flex flex-col items-center gap-1 justify-center max-w-[310px]"
          >
            <Link to={`/items/${it.id}/?prod=${it.title}`}>
              <img
                src={it.thumbnail}
                width={140}
                height={100}
                alt={it.description}
              />
              <p className="text-sm text-blue-800 font-bold ">
                {it.title.substring(0, 20).concat("...")}
              </p>
              {/* <p>{it.id}</p> */}
            </Link>

            <div className="">
              <Rate
                style={{
                  fontSize: "0.8rem",
                }}
                allowHalf
                disabled
                defaultValue={it.rating}
              />
              <div className=" font-bold text-lg flex justify-around items-center gap-1  w-full">
                <b>$ {it.price}</b>

                <CartIcon />
              </div>
            </div>
          </div>
        ))}
      </main>
      <Pagination />
      <BackToTop />

      <Drawer
        // title="Drawer with extra actions"
        placement={placement}
        width={300}
        onClose={onClose}
        open={open}
        className="z-[1001] "
        // extra={
        //   <Space>
        //     <Button onClick={onClose}>Cancel</Button>
        //     <Button type="primary" onClick={onClose}>
        //       OK
        //     </Button>
        //   </Space>
        // }
      >
        {/* <FiltersSide /> */}
      </Drawer>
      <Footer />
    </div>
  );
};

export default Categories;
