import React, { useEffect, useState } from "react";
import { Helmet } from "react-helmet";
import { Header } from "../Components/Header/Header";
import { useQuery } from "react-query";
import { getAllOrders } from "../utils/apis";
import LoadingComp from "../Components/Common-Comp/LoadingComp";
import { getUserId } from "../helpers/loggedUser";

const Order = () => {
	const { data: orders, isLoading } = useQuery("getallorders", getAllOrders);
	const userId = getUserId();
	const [ordersData, setOrdersData] = useState();

	useEffect(() => {
		if (orders?.data) {
			setOrdersData(()=>orders?.data)
		}
	}, orders?.data)
	
  return (
    <div>
      <Helmet>
        <title>My Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fursanFavIcon.svg" />
      </Helmet>
      <Header />
      <div>
        {isLoading ? (
          <div></div>
        ) : (
          <div>
            <LoadingComp />
          </div>
        )}
      </div>
    </div>
  );
};

export default Order;
