import { Helmet } from "react-helmet";
import { Header } from "../Components/Header/Header";
import { Footer } from "../Components/Footer/Footer";
import { BsBoxSeamFill } from "react-icons/bs";
import { MdKeyboardArrowRight } from "react-icons/md";
import { FaUser } from "react-icons/fa";
import { useState } from "react";

const ProfilePge = () => {
  const [selectedAccSett, setSelectedAccSett] = useState("");

  return (
    <div className="w-full h-full">
      <Helmet>
        <title>My Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fursanFavIcon.svg" />
      </Helmet>
      <Header />
      <div className="mx-auto bg-slate-300 max-w-[1200px] h-[500px] flex gap-3 border">
        <div className="bg-white w-1/3 h-full flex flex-col gap-3">
          <div className="p-5 flex gap-5 items-center border">
            <img
              src="https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?size=338&ext=jpg&ga=GA1.1.1518270500.1717459200&semt=ais_user"
              alt="profile"
              className="w-16 rounded-full"
            />
            <div>
              <p>Hello,</p>
              <h2 className="font-semibold">Niyad</h2>
            </div>
          </div>
          <div className="border">
            {/* my order */}
            <div className="flex justify-between items-center p-5 border-b">
              <h2 className="flex gap-2 items-center text-lg font-bold">
                <span>
                  <BsBoxSeamFill className="text-amber-400" />
                </span>{" "}
                MY ORDERS
              </h2>
              <span>
                <MdKeyboardArrowRight size={25} />
              </span>
            </div>
            {/* account settings */}
            <div>
              <div className="flex justify-between items-center p-5">
                <h2 className="flex gap-2 items-center text-lg font-bold">
                  <span>
                    <FaUser className="text-amber-400" />
                  </span>{" "}
                  ACCOUNT SETTINGS
                </h2>
              </div>
              <div
                className={`p-3 hover:bg-amber-200 ${
                  selectedAccSett === "profileInfo" ?? "bg-amber-200"
                }`}
                onClick={() => setSelectedAccSett("profileInfo")}
              >
                <h3 className="pl-10 font-medium">Profile Information</h3>
              </div>
              <div
                className={`p-3 hover:bg-amber-200 ${
                  selectedAccSett === "manageAddress" ?? "bg-amber-200"
                }`}
                onClick={() => setSelectedAccSett("manageAddress")}
              >
                <h3 className="pl-10 font-medium">Manage Address</h3>
              </div>
              <div
                className={`p-3 hover:bg-amber-200 ${
                  selectedAccSett === "activityLog" ?? "bg-amber-200"
                } `}
                onClick={() => setSelectedAccSett("activityLog")}
              >
                <h3 className="pl-10 font-medium">Activity log</h3>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white w-2/3 h-full"></div>
      </div>
      <Footer />
    </div>
  );
};

export default ProfilePge;
