import { Button, Input } from "antd";
import { useState } from "react";
import { Helmet } from "react-helmet";
import { BsBoxSeamFill } from "react-icons/bs";
import { FaUser } from "react-icons/fa";
import { MdKeyboardArrowRight } from "react-icons/md";
import { useQuery } from "react-query";
import { Footer } from "../Components/Footer/Footer";
import { Header } from "../Components/Header/Header";
import { getUserId } from "../helpers/loggedUser";
import { getUserById } from "../utils/apis";

const ProfilePge = () => {
  const [selectedAccSett, setSelectedAccSett] = useState("profileInfo");
  const [editUserName, setEditUserName] = useState(false);
  const [editEmail, setEditEmail] = useState(false);
  const [editPhone, setEditPone] = useState(false);
  const userId = getUserId() || "";
  const isUserId = !!userId;

  const { data } = useQuery("getuserbyid", () => getUserById(userId), {
    enabled: isUserId,
  });

  return (
    <div className="w-full h-full">
      <Helmet>
        <title>My Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fursanFavIcon.svg" />
      </Helmet>
      <Header />
      <div className="mx-auto bg-slate-300 max-w-[1200px] h-[500px] flex gap-3 border">
        <div className="bg-white w-1/3 h-full flex flex-col gap-3">
          <div className="p-5 flex gap-5 items-center border">
            <img
              src="https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?size=338&ext=jpg&ga=GA1.1.1518270500.1717459200&semt=ais_user"
              alt="profile"
              className="w-16 rounded-full"
            />
            <div>
              <p>Hello,</p>
              <h2 className="font-semibold">{data?.data?.username}</h2>
            </div>
          </div>
          <div className="border">
            {/* my order */}
            <div className="flex justify-between items-center p-5 border-b">
              <h2 className="flex gap-2 items-center text-lg font-bold">
                <span>
                  <BsBoxSeamFill className="text-amber-400" />
                </span>{" "}
                MY ORDERS
              </h2>
              <span>
                <MdKeyboardArrowRight size={25} />
              </span>
            </div>
            {/* account settings */}
            <div>
              <div className="flex justify-between items-center p-5">
                <h2 className="flex gap-2 items-center text-lg font-bold">
                  <span>
                    <FaUser className="text-amber-400" />
                  </span>{" "}
                  ACCOUNT SETTINGS
                </h2>
              </div>
              <div
                className={`p-3 hover:bg-amber-200 ${
                  selectedAccSett === "profileInfo" ?? "bg-amber-200"
                }`}
                onClick={() => setSelectedAccSett("profileInfo")}
              >
                <h3 className="pl-10 font-medium">Profile Information</h3>
              </div>
              <div
                className={`p-3 hover:bg-amber-200 ${
                  selectedAccSett === "manageAddress" ?? "bg-amber-200"
                }`}
                onClick={() => setSelectedAccSett("manageAddress")}
              >
                <h3 className="pl-10 font-medium">Manage Address</h3>
              </div>
              <div
                className={`p-3 hover:bg-amber-200 ${
                  selectedAccSett === "activityLog" ?? "bg-amber-200"
                } `}
                onClick={() => setSelectedAccSett("activityLog")}
              >
                <h3 className="pl-10 font-medium">Activity log</h3>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white w-2/3 h-full p-10">
          <div
            className={`${
              selectedAccSett === "profileInfo" ? "block" : "hidden"
            }`}
          >
            <div className="mb-5">
              <div className="flex items-center gap-5 mb-3">
                <h3 className="font-semibold">Personal Information</h3>
                <span
                  className="text-xs cursor-pointer hover:text-blue-500"
                  onClick={() => setEditUserName((prev) => !prev)}
                >
                  Edit
                </span>
              </div>
              <div className="flex gap-3 items-center">
                <Input
                  value={data?.data?.username}
                  placeholder="Enter user name"
                  disabled={!editUserName}
                  className="p-3 text-lg max-w-[300px]"
                />
                <Button
                  className={`bg-amber-400 text-white ${
                    !editUserName ? "hidden" : "block"
                  } `}
                >
                  Save
                </Button>
              </div>
            </div>
            <div className="mb-5">
              <div className="flex items-center gap-5 mb-3">
                <h3 className="font-semibold">Email Address</h3>
                <span
                  className="text-xs cursor-pointer hover:text-blue-500"
                  onClick={() => setEditEmail((prev) => !prev)}
                >
                  Edit
                </span>
              </div>
              <div className="flex gap-3 items-center">
                <Input
                  value={data?.data?.email}
                  placeholder="Enter email address"
                  disabled={!editEmail}
                  className="p-3 text-lg max-w-[300px]"
                />
                <Button
                  className={`bg-amber-400 text-white ${
                    !editEmail ? "hidden" : "block"
                  } `}
                >
                  Save
                </Button>
              </div>
            </div>
            <div className="mb-5">
              <div className="flex items-center gap-5 mb-3">
                <h3 className="font-semibold">Mobail Number</h3>
                <span
                  className="text-xs cursor-pointer hover:text-blue-500"
                  onClick={() => setEditPone((prev) => !prev)}
                >
                  Edit
                </span>
              </div>
              <div className="flex gap-3 items-center">
                <Input
                  value={data?.data?.phone}
                  placeholder="Enter phone number"
                  disabled={!editPhone}
                  className="p-3 text-lg max-w-[300px]"
                />
                <Button
                  className={`bg-amber-400 text-white ${
                    !editPhone ? "hidden" : "block"
                  } `}
                >
                  Save
                </Button>
              </div>
            </div>
          </div>
          {/* address area */}
          <div className={`${
              selectedAccSett === "manageAddress" ? "block" : "hidden"
            }`}>
            <div className="mb-5">
              <div className="flex items-center gap-5 mb-3">
                <h3 className="font-semibold">Manage Address</h3>
                <span
                  className="text-xs cursor-pointer hover:text-blue-500"
                  onClick={() => setEditUserName((prev) => !prev)}
                >
                  Edit
                </span>
              </div>
              <div className="flex gap-3 items-center">
                <Input
                  defaultValue={data?.data?.username}
                  placeholder="Enter user name"
                  disabled={!editUserName}
                  className="p-3 text-lg max-w-[300px]"
                />
                <Button
                  className={`bg-amber-400 text-white ${
                    !editUserName ? "hidden" : "block"
                  } `}
                >
                  Save
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default ProfilePge;
